# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redukti/bootstrap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from redukti import enums_pb2 as redukti_dot_enums__pb2
from redukti import curve_pb2 as redukti_dot_curve__pb2
from redukti import shared_pb2 as redukti_dot_shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='redukti/bootstrap.proto',
  package='redukti',
  syntax='proto3',
  serialized_options=_b('\n\021com.redukti.typesB\005TypesP\001\370\001\001\252\002\rRedukti.Types'),
  serialized_pb=_b('\n\x17redukti/bootstrap.proto\x12\x07redukti\x1a\x13redukti/enums.proto\x1a\x13redukti/curve.proto\x1a\x14redukti/shared.proto\"\xb3\x01\n\rParInstrument\x12\x17\n\x0finstrument_type\x18\x01 \x01(\t\x12\x16\n\x0einstrument_key\x18\x02 \x01(\t\x12$\n\x1c\x64iscount_curve_definition_id\x18\x03 \x01(\x05\x12#\n\x1b\x66orward_curve_definition_id\x18\x04 \x01(\x05\x12&\n\x0e\x66loating_tenor\x18\x05 \x01(\x0e\x32\x0e.redukti.Tenor\"2\n\x08ParRates\x12\x16\n\x0einstrument_ids\x18\x01 \x03(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x01\"z\n\x08ParCurve\x12\x1b\n\x13\x63urve_definition_id\x18\x01 \x01(\x05\x12+\n\x0binstruments\x18\x02 \x03(\x0b\x32\x16.redukti.ParInstrument\x12$\n\tpar_rates\x18\x03 \x01(\x0b\x32\x11.redukti.ParRates\"\x9a\x01\n\x0bParCurveSet\x12\x12\n\nas_of_date\x18\x01 \x01(\x05\x12\r\n\x05\x63ycle\x18\x02 \x01(\x05\x12/\n\tqualifier\x18\x03 \x01(\x0e\x32\x1c.redukti.MarketDataQualifier\x12\x10\n\x08scenario\x18\x04 \x01(\x05\x12%\n\npar_curves\x18\x05 \x03(\x0b\x32\x11.redukti.ParCurve\"\x80\x02\n\x16\x42ootstrapCurvesRequest\x12\x15\n\rbusiness_date\x18\x01 \x01(\x05\x12\x35\n\x11\x63urve_definitions\x18\x02 \x03(\x0b\x32\x1a.redukti.IRCurveDefinition\x12+\n\rpar_curve_set\x18\x03 \x01(\x0b\x32\x14.redukti.ParCurveSet\x12\"\n\x1agenerate_par_sensitivities\x18\x04 \x01(\x08\x12(\n\x0bsolver_type\x18\x05 \x01(\x0e\x32\x13.redukti.SolverType\x12\x1d\n\x15max_solver_iterations\x18\x06 \x01(\x05\"\x9f\x01\n\x14\x42ootstrapCurvesReply\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.redukti.ReplyHeader\x12\"\n\x06\x63urves\x18\x02 \x03(\x0b\x32\x12.redukti.ZeroCurve\x12=\n\x11par_sensitivities\x18\x03 \x03(\x0b\x32\".redukti.ZeroCurveParSensitivities*w\n\nSolverType\x12#\n\x1fSOLVER_TYPE_LEVENBERG_MARQUARDT\x10\x00\x12#\n\x1fSOLVER_TYPE_LINEAR_LEAST_SQUARE\x10\x01\x12\x1f\n\x1bSOLVER_TYPE_LINEAR_LUFACTOR\x10\x02\x42/\n\x11\x63om.redukti.typesB\x05TypesP\x01\xf8\x01\x01\xaa\x02\rRedukti.Typesb\x06proto3')
  ,
  dependencies=[redukti_dot_enums__pb2.DESCRIPTOR,redukti_dot_curve__pb2.DESCRIPTOR,redukti_dot_shared__pb2.DESCRIPTOR,])

_SOLVERTYPE = _descriptor.EnumDescriptor(
  name='SolverType',
  full_name='redukti.SolverType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOLVER_TYPE_LEVENBERG_MARQUARDT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOLVER_TYPE_LINEAR_LEAST_SQUARE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOLVER_TYPE_LINEAR_LUFACTOR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1036,
  serialized_end=1155,
)
_sym_db.RegisterEnumDescriptor(_SOLVERTYPE)

SolverType = enum_type_wrapper.EnumTypeWrapper(_SOLVERTYPE)
SOLVER_TYPE_LEVENBERG_MARQUARDT = 0
SOLVER_TYPE_LINEAR_LEAST_SQUARE = 1
SOLVER_TYPE_LINEAR_LUFACTOR = 2



_PARINSTRUMENT = _descriptor.Descriptor(
  name='ParInstrument',
  full_name='redukti.ParInstrument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_type', full_name='redukti.ParInstrument.instrument_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrument_key', full_name='redukti.ParInstrument.instrument_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discount_curve_definition_id', full_name='redukti.ParInstrument.discount_curve_definition_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forward_curve_definition_id', full_name='redukti.ParInstrument.forward_curve_definition_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floating_tenor', full_name='redukti.ParInstrument.floating_tenor', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=280,
)


_PARRATES = _descriptor.Descriptor(
  name='ParRates',
  full_name='redukti.ParRates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_ids', full_name='redukti.ParRates.instrument_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='redukti.ParRates.values', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=332,
)


_PARCURVE = _descriptor.Descriptor(
  name='ParCurve',
  full_name='redukti.ParCurve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve_definition_id', full_name='redukti.ParCurve.curve_definition_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instruments', full_name='redukti.ParCurve.instruments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='par_rates', full_name='redukti.ParCurve.par_rates', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=456,
)


_PARCURVESET = _descriptor.Descriptor(
  name='ParCurveSet',
  full_name='redukti.ParCurveSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_of_date', full_name='redukti.ParCurveSet.as_of_date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='redukti.ParCurveSet.cycle', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qualifier', full_name='redukti.ParCurveSet.qualifier', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scenario', full_name='redukti.ParCurveSet.scenario', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='par_curves', full_name='redukti.ParCurveSet.par_curves', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=613,
)


_BOOTSTRAPCURVESREQUEST = _descriptor.Descriptor(
  name='BootstrapCurvesRequest',
  full_name='redukti.BootstrapCurvesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='business_date', full_name='redukti.BootstrapCurvesRequest.business_date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curve_definitions', full_name='redukti.BootstrapCurvesRequest.curve_definitions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='par_curve_set', full_name='redukti.BootstrapCurvesRequest.par_curve_set', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generate_par_sensitivities', full_name='redukti.BootstrapCurvesRequest.generate_par_sensitivities', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solver_type', full_name='redukti.BootstrapCurvesRequest.solver_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_solver_iterations', full_name='redukti.BootstrapCurvesRequest.max_solver_iterations', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=872,
)


_BOOTSTRAPCURVESREPLY = _descriptor.Descriptor(
  name='BootstrapCurvesReply',
  full_name='redukti.BootstrapCurvesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='redukti.BootstrapCurvesReply.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curves', full_name='redukti.BootstrapCurvesReply.curves', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='par_sensitivities', full_name='redukti.BootstrapCurvesReply.par_sensitivities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=875,
  serialized_end=1034,
)

_PARINSTRUMENT.fields_by_name['floating_tenor'].enum_type = redukti_dot_enums__pb2._TENOR
_PARCURVE.fields_by_name['instruments'].message_type = _PARINSTRUMENT
_PARCURVE.fields_by_name['par_rates'].message_type = _PARRATES
_PARCURVESET.fields_by_name['qualifier'].enum_type = redukti_dot_enums__pb2._MARKETDATAQUALIFIER
_PARCURVESET.fields_by_name['par_curves'].message_type = _PARCURVE
_BOOTSTRAPCURVESREQUEST.fields_by_name['curve_definitions'].message_type = redukti_dot_curve__pb2._IRCURVEDEFINITION
_BOOTSTRAPCURVESREQUEST.fields_by_name['par_curve_set'].message_type = _PARCURVESET
_BOOTSTRAPCURVESREQUEST.fields_by_name['solver_type'].enum_type = _SOLVERTYPE
_BOOTSTRAPCURVESREPLY.fields_by_name['header'].message_type = redukti_dot_shared__pb2._REPLYHEADER
_BOOTSTRAPCURVESREPLY.fields_by_name['curves'].message_type = redukti_dot_curve__pb2._ZEROCURVE
_BOOTSTRAPCURVESREPLY.fields_by_name['par_sensitivities'].message_type = redukti_dot_curve__pb2._ZEROCURVEPARSENSITIVITIES
DESCRIPTOR.message_types_by_name['ParInstrument'] = _PARINSTRUMENT
DESCRIPTOR.message_types_by_name['ParRates'] = _PARRATES
DESCRIPTOR.message_types_by_name['ParCurve'] = _PARCURVE
DESCRIPTOR.message_types_by_name['ParCurveSet'] = _PARCURVESET
DESCRIPTOR.message_types_by_name['BootstrapCurvesRequest'] = _BOOTSTRAPCURVESREQUEST
DESCRIPTOR.message_types_by_name['BootstrapCurvesReply'] = _BOOTSTRAPCURVESREPLY
DESCRIPTOR.enum_types_by_name['SolverType'] = _SOLVERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParInstrument = _reflection.GeneratedProtocolMessageType('ParInstrument', (_message.Message,), dict(
  DESCRIPTOR = _PARINSTRUMENT,
  __module__ = 'redukti.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:redukti.ParInstrument)
  ))
_sym_db.RegisterMessage(ParInstrument)

ParRates = _reflection.GeneratedProtocolMessageType('ParRates', (_message.Message,), dict(
  DESCRIPTOR = _PARRATES,
  __module__ = 'redukti.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:redukti.ParRates)
  ))
_sym_db.RegisterMessage(ParRates)

ParCurve = _reflection.GeneratedProtocolMessageType('ParCurve', (_message.Message,), dict(
  DESCRIPTOR = _PARCURVE,
  __module__ = 'redukti.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:redukti.ParCurve)
  ))
_sym_db.RegisterMessage(ParCurve)

ParCurveSet = _reflection.GeneratedProtocolMessageType('ParCurveSet', (_message.Message,), dict(
  DESCRIPTOR = _PARCURVESET,
  __module__ = 'redukti.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:redukti.ParCurveSet)
  ))
_sym_db.RegisterMessage(ParCurveSet)

BootstrapCurvesRequest = _reflection.GeneratedProtocolMessageType('BootstrapCurvesRequest', (_message.Message,), dict(
  DESCRIPTOR = _BOOTSTRAPCURVESREQUEST,
  __module__ = 'redukti.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:redukti.BootstrapCurvesRequest)
  ))
_sym_db.RegisterMessage(BootstrapCurvesRequest)

BootstrapCurvesReply = _reflection.GeneratedProtocolMessageType('BootstrapCurvesReply', (_message.Message,), dict(
  DESCRIPTOR = _BOOTSTRAPCURVESREPLY,
  __module__ = 'redukti.bootstrap_pb2'
  # @@protoc_insertion_point(class_scope:redukti.BootstrapCurvesReply)
  ))
_sym_db.RegisterMessage(BootstrapCurvesReply)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
