# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redukti/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from redukti import enums_pb2 as redukti_dot_enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='redukti/common.proto',
  package='redukti',
  syntax='proto3',
  serialized_options=_b('\n\021com.redukti.typesB\005TypesP\001\370\001\001\252\002\rRedukti.Types'),
  serialized_pb=_b('\n\x14redukti/common.proto\x12\x07redukti\x1a\x13redukti/enums.proto*N\n\x13StandardRequestType\x12\x0b\n\x07SRT_ADD\x10\x00\x12\x0c\n\x08SRT_SAVE\x10\x01\x12\x0e\n\nSRT_DELETE\x10\x02\x12\x0c\n\x08SRT_FIND\x10\x03\x42/\n\x11\x63om.redukti.typesB\x05TypesP\x01\xf8\x01\x01\xaa\x02\rRedukti.Typesb\x06proto3')
  ,
  dependencies=[redukti_dot_enums__pb2.DESCRIPTOR,])

_STANDARDREQUESTTYPE = _descriptor.EnumDescriptor(
  name='StandardRequestType',
  full_name='redukti.StandardRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SRT_ADD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SRT_SAVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SRT_DELETE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SRT_FIND', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=54,
  serialized_end=132,
)
_sym_db.RegisterEnumDescriptor(_STANDARDREQUESTTYPE)

StandardRequestType = enum_type_wrapper.EnumTypeWrapper(_STANDARDREQUESTTYPE)
SRT_ADD = 0
SRT_SAVE = 1
SRT_DELETE = 2
SRT_FIND = 3


DESCRIPTOR.enum_types_by_name['StandardRequestType'] = _STANDARDREQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
