# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redukti/curve.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from redukti import enums_pb2 as redukti_dot_enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='redukti/curve.proto',
  package='redukti',
  syntax='proto3',
  serialized_options=_b('\n\021com.redukti.typesB\005TypesP\001\370\001\001\252\002\rRedukti.Types'),
  serialized_pb=_b('\n\x13redukti/curve.proto\x12\x07redukti\x1a\x13redukti/enums.proto\"\x80\x03\n\x11IRCurveDefinition\x12\n\n\x02id\x18\x01 \x01(\x05\x12(\n\x0b\x63urve_group\x18\x02 \x01(\x0e\x32\x13.redukti.CurveGroup\x12#\n\x08\x63urrency\x18\x03 \x01(\x0e\x32\x11.redukti.Currency\x12*\n\x0cindex_family\x18\x04 \x01(\x0e\x32\x14.redukti.IndexFamily\x12\x1d\n\x05tenor\x18\x05 \x01(\x0e\x32\x0e.redukti.Tenor\x12\x34\n\x11interpolator_type\x18\x06 \x01(\x0e\x32\x19.redukti.InterpolatorType\x12,\n\x0finterpolated_on\x18\x07 \x01(\x0e\x32\x13.redukti.IRRateType\x12\x41\n\x18maturity_generation_rule\x18\x08 \x01(\x0e\x32\x1f.redukti.MaturityGenerationRule\x12\x1e\n\x06tenors\x18\t \x03(\x0e\x32\x0e.redukti.Tenor\"L\n\tZeroCurve\x12\x1b\n\x13\x63urve_definition_id\x18\x01 \x01(\x05\x12\x12\n\nmaturities\x18\x02 \x03(\x05\x12\x0e\n\x06values\x18\x03 \x03(\x01\"\xd8\x01\n\x19ZeroCurveParSensitivities\x12\x1b\n\x13\x63urve_definition_id\x18\x01 \x01(\x05\x12\x17\n\x0fnum_instruments\x18\x02 \x01(\x05\x12\x16\n\x0enum_maturities\x18\x03 \x01(\x05\x12>\n\x06values\x18\x04 \x03(\x0b\x32..redukti.ZeroCurveParSensitivities.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\xb0\x02\n\x0cZeroCurveSet\x12\x12\n\nas_of_date\x18\x01 \x01(\x05\x12\r\n\x05\x63ycle\x18\x02 \x01(\x05\x12/\n\tqualifier\x18\x03 \x01(\x0e\x32\x1c.redukti.MarketDataQualifier\x12\x10\n\x08scenario\x18\x04 \x01(\x05\x12(\n\x0b\x63urve_group\x18\x05 \x01(\x0e\x32\x13.redukti.CurveGroup\x12#\n\x08\x63urrency\x18\x06 \x01(\x0e\x32\x11.redukti.Currency\x12\'\n\x0bzero_curves\x18\x07 \x03(\x0b\x32\x12.redukti.ZeroCurve\x12\x42\n\x16zero_par_sensitivities\x18\x08 \x03(\x0b\x32\".redukti.ZeroCurveParSensitivitiesB/\n\x11\x63om.redukti.typesB\x05TypesP\x01\xf8\x01\x01\xaa\x02\rRedukti.Typesb\x06proto3')
  ,
  dependencies=[redukti_dot_enums__pb2.DESCRIPTOR,])




_IRCURVEDEFINITION = _descriptor.Descriptor(
  name='IRCurveDefinition',
  full_name='redukti.IRCurveDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='redukti.IRCurveDefinition.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curve_group', full_name='redukti.IRCurveDefinition.curve_group', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='redukti.IRCurveDefinition.currency', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_family', full_name='redukti.IRCurveDefinition.index_family', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenor', full_name='redukti.IRCurveDefinition.tenor', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interpolator_type', full_name='redukti.IRCurveDefinition.interpolator_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interpolated_on', full_name='redukti.IRCurveDefinition.interpolated_on', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maturity_generation_rule', full_name='redukti.IRCurveDefinition.maturity_generation_rule', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenors', full_name='redukti.IRCurveDefinition.tenors', index=8,
      number=9, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=438,
)


_ZEROCURVE = _descriptor.Descriptor(
  name='ZeroCurve',
  full_name='redukti.ZeroCurve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve_definition_id', full_name='redukti.ZeroCurve.curve_definition_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maturities', full_name='redukti.ZeroCurve.maturities', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='redukti.ZeroCurve.values', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=516,
)


_ZEROCURVEPARSENSITIVITIES_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='redukti.ZeroCurveParSensitivities.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='redukti.ZeroCurveParSensitivities.ValuesEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='redukti.ZeroCurveParSensitivities.ValuesEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=735,
)

_ZEROCURVEPARSENSITIVITIES = _descriptor.Descriptor(
  name='ZeroCurveParSensitivities',
  full_name='redukti.ZeroCurveParSensitivities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve_definition_id', full_name='redukti.ZeroCurveParSensitivities.curve_definition_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_instruments', full_name='redukti.ZeroCurveParSensitivities.num_instruments', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_maturities', full_name='redukti.ZeroCurveParSensitivities.num_maturities', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='redukti.ZeroCurveParSensitivities.values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ZEROCURVEPARSENSITIVITIES_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=735,
)


_ZEROCURVESET = _descriptor.Descriptor(
  name='ZeroCurveSet',
  full_name='redukti.ZeroCurveSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_of_date', full_name='redukti.ZeroCurveSet.as_of_date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='redukti.ZeroCurveSet.cycle', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qualifier', full_name='redukti.ZeroCurveSet.qualifier', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scenario', full_name='redukti.ZeroCurveSet.scenario', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curve_group', full_name='redukti.ZeroCurveSet.curve_group', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='redukti.ZeroCurveSet.currency', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zero_curves', full_name='redukti.ZeroCurveSet.zero_curves', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zero_par_sensitivities', full_name='redukti.ZeroCurveSet.zero_par_sensitivities', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=1042,
)

_IRCURVEDEFINITION.fields_by_name['curve_group'].enum_type = redukti_dot_enums__pb2._CURVEGROUP
_IRCURVEDEFINITION.fields_by_name['currency'].enum_type = redukti_dot_enums__pb2._CURRENCY
_IRCURVEDEFINITION.fields_by_name['index_family'].enum_type = redukti_dot_enums__pb2._INDEXFAMILY
_IRCURVEDEFINITION.fields_by_name['tenor'].enum_type = redukti_dot_enums__pb2._TENOR
_IRCURVEDEFINITION.fields_by_name['interpolator_type'].enum_type = redukti_dot_enums__pb2._INTERPOLATORTYPE
_IRCURVEDEFINITION.fields_by_name['interpolated_on'].enum_type = redukti_dot_enums__pb2._IRRATETYPE
_IRCURVEDEFINITION.fields_by_name['maturity_generation_rule'].enum_type = redukti_dot_enums__pb2._MATURITYGENERATIONRULE
_IRCURVEDEFINITION.fields_by_name['tenors'].enum_type = redukti_dot_enums__pb2._TENOR
_ZEROCURVEPARSENSITIVITIES_VALUESENTRY.containing_type = _ZEROCURVEPARSENSITIVITIES
_ZEROCURVEPARSENSITIVITIES.fields_by_name['values'].message_type = _ZEROCURVEPARSENSITIVITIES_VALUESENTRY
_ZEROCURVESET.fields_by_name['qualifier'].enum_type = redukti_dot_enums__pb2._MARKETDATAQUALIFIER
_ZEROCURVESET.fields_by_name['curve_group'].enum_type = redukti_dot_enums__pb2._CURVEGROUP
_ZEROCURVESET.fields_by_name['currency'].enum_type = redukti_dot_enums__pb2._CURRENCY
_ZEROCURVESET.fields_by_name['zero_curves'].message_type = _ZEROCURVE
_ZEROCURVESET.fields_by_name['zero_par_sensitivities'].message_type = _ZEROCURVEPARSENSITIVITIES
DESCRIPTOR.message_types_by_name['IRCurveDefinition'] = _IRCURVEDEFINITION
DESCRIPTOR.message_types_by_name['ZeroCurve'] = _ZEROCURVE
DESCRIPTOR.message_types_by_name['ZeroCurveParSensitivities'] = _ZEROCURVEPARSENSITIVITIES
DESCRIPTOR.message_types_by_name['ZeroCurveSet'] = _ZEROCURVESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IRCurveDefinition = _reflection.GeneratedProtocolMessageType('IRCurveDefinition', (_message.Message,), dict(
  DESCRIPTOR = _IRCURVEDEFINITION,
  __module__ = 'redukti.curve_pb2'
  # @@protoc_insertion_point(class_scope:redukti.IRCurveDefinition)
  ))
_sym_db.RegisterMessage(IRCurveDefinition)

ZeroCurve = _reflection.GeneratedProtocolMessageType('ZeroCurve', (_message.Message,), dict(
  DESCRIPTOR = _ZEROCURVE,
  __module__ = 'redukti.curve_pb2'
  # @@protoc_insertion_point(class_scope:redukti.ZeroCurve)
  ))
_sym_db.RegisterMessage(ZeroCurve)

ZeroCurveParSensitivities = _reflection.GeneratedProtocolMessageType('ZeroCurveParSensitivities', (_message.Message,), dict(

  ValuesEntry = _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _ZEROCURVEPARSENSITIVITIES_VALUESENTRY,
    __module__ = 'redukti.curve_pb2'
    # @@protoc_insertion_point(class_scope:redukti.ZeroCurveParSensitivities.ValuesEntry)
    ))
  ,
  DESCRIPTOR = _ZEROCURVEPARSENSITIVITIES,
  __module__ = 'redukti.curve_pb2'
  # @@protoc_insertion_point(class_scope:redukti.ZeroCurveParSensitivities)
  ))
_sym_db.RegisterMessage(ZeroCurveParSensitivities)
_sym_db.RegisterMessage(ZeroCurveParSensitivities.ValuesEntry)

ZeroCurveSet = _reflection.GeneratedProtocolMessageType('ZeroCurveSet', (_message.Message,), dict(
  DESCRIPTOR = _ZEROCURVESET,
  __module__ = 'redukti.curve_pb2'
  # @@protoc_insertion_point(class_scope:redukti.ZeroCurveSet)
  ))
_sym_db.RegisterMessage(ZeroCurveSet)


DESCRIPTOR._options = None
_ZEROCURVEPARSENSITIVITIES_VALUESENTRY._options = None
# @@protoc_insertion_point(module_scope)
