# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from redukti import services_pb2 as redukti_dot_services__pb2


class OpenReduktiServicesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.serve = channel.unary_unary(
        '/redukti.OpenReduktiServices/serve',
        request_serializer=redukti_dot_services__pb2.Request.SerializeToString,
        response_deserializer=redukti_dot_services__pb2.Response.FromString,
        )


class OpenReduktiServicesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def serve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OpenReduktiServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'serve': grpc.unary_unary_rpc_method_handler(
          servicer.serve,
          request_deserializer=redukti_dot_services__pb2.Request.FromString,
          response_serializer=redukti_dot_services__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'redukti.OpenReduktiServices', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
